import { Article } from './Article';

export const ARTICLES: Article[] = [
  { id: 0, order: "#1", mainPoint: "Melanoma statistics", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 1, order: "#2", mainPoint: "The best way to cure melanoma", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 2, order: "#3", mainPoint: "What to do if a suspicious mole appears", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 3, order: "#4", mainPoint: "What to do if a suspicious mole appears", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 4, order: "#5", mainPoint: "What to do if a suspicious mole appears", content: "TEST TEXT hat other factors may contribute to your risk of melanoma." },
  { id: 1, order: "#2", mainPoint: "The best way to cure melanoma", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 2, order: "#3", mainPoint: "What to do if a suspicious mole appears", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 3, order: "#4", mainPoint: "What to do if a suspicious mole appears", content: "Melanoma occurs when something goes wrong in the melanin-producing cells (melanocytes) that give color to your skin." +
      "Normally, skin cells develop in a controlled and orderly way — healthy new cells push older cells toward your skin's surface, where they die and eventually fall off. But when some cells develop DNA damage, new cells may begin to grow out of control and can eventually form a mass of cancerous cells." +
      "Just what damages DNA in skin cells and how this leads to melanoma isn't clear. It's likely that a combination of factors, including environmental and genetic factors, causes melanoma. Still, doctors believe exposure to ultraviolet (UV) radiation from the sun and from tanning lamps and beds is the leading cause of melanoma." +
      "UV light doesn't cause all melanomas, especially those that occur in places on your body that don't receive exposure to sunlight. This indicates that other factors may contribute to your risk of melanoma." },
  { id: 4, order: "#5", mainPoint: "What to do if a suspicious mole appears", content: "TEST TEXT hat other factors may contribute to your risk of melanoma." },

];
