"""remove-slug-specialist

Revision ID: de8355975a1c
Revises: f2d93bbf10bf
Create Date: 2022-11-22 05:32:32.168251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8355975a1c'
down_revision = 'f2d93bbf10bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
