"""init

Revision ID: f2d93bbf10bf
Revises: 
Create Date: 2022-11-22 04:46:48.009669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d93bbf10bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url_source', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('html_content', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinics', sa.String(), nullable=True),
    sa.Column('doctor', sa.String(), nullable=True),
    sa.Column('web', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('online_reservation', sa.String(), nullable=True),
    sa.Column('health_insurance', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist')
    op.drop_table('article')
    # ### end Alembic commands ###
